'\" t
.TH groff_ms @MAN7EXT@ "@MDATE@" "groff @VERSION@"
.SH Name
groff_ms \- GNU roff manuscript macro package for formatting documents
.
.
.\" ====================================================================
.\" Legal Terms
.\" ====================================================================
.\"
.\" Copyright (C) 1989-2021 Free Software Foundation, Inc.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided that
.\" the entire resulting derived work is distributed under the terms of
.\" a permission notice identical to this one.
.\"
.\" Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for
.\" modified versions, except that this permission notice may be
.\" included in translations approved by the Free Software Foundation
.\" instead of in the original English.
.
.
.\" Save and disable compatibility mode (for, e.g., Solaris 10/11).
.do nr *groff_groff_ms_7_man_C \n[.cp]
.cp 0
.
.
.\" ====================================================================
.SH Synopsis
.\" ====================================================================
.
.SY "groff \-ms"
.RI [ option
\&.\|.\|.\&]
.RI [ input-file
\&.\|.\|.\&]
.
.SY "groff \-m ms"
.RI [ option
\&.\|.\|.\&]
.RI [ input-file
\&.\|.\|.\&]
.YS
.
.
.\" ====================================================================
.SH Description
.\" ====================================================================
.
The GNU implementation of the
.I ms
macros is part of the
.I groff
typesetting system.
.
The
.I ms
package is suitable for the composition of
letters,
memoranda,
reports,
and books.
.
.
.LP
These
.I groff
macros support cover page and table of contents generation,
automatic section numbering,
several different paragraph styles,
a variety of text styling options,
footnotes,
multi-column page layouts,
and indexing.
.
.I ms
supports the
.IR \%@g@tbl (@MAN1EXT@),
.IR \%@g@eqn (@MAN1EXT@),
.IR \%@g@pic (@MAN1EXT@),
and
.IR \%@g@refer (@MAN1EXT@)
preprocessors for inclusion of tables,
mathematical equations,
diagrams,
and standardized bibliographic citations.
.
.
.LP
This implementation is mostly compatible with the documented interface
and behavior of AT&T Version\~7 Unix
.IR ms .
.
Several extensions from 4.2BSD
.\" Few changes were made in 4.3, Reno, Tahoe, or 4.4.
and Version\~10 Research Unix have been recreated.
.
.
.\" ====================================================================
.SH Usage
.\" ====================================================================
.
The
.I ms
macro package expects files to have a certain amount of structure.
.
The simplest documents can begin with a paragraph macro and consist of
text separated by paragraph macros or even blank lines.
.
Longer documents have a structure as follows.
.
.
.TP
.B Document type
If you call the
.B RP
macro at the beginning of the document,
.I groff
prints the document description on its own page;
otherwise it prints the information
(if any)
on the first page with your document text immediately following.
.
Some document types found in other
.I ms
implementations are specific to AT&T or Berkeley,
and are not supported in
.IR "groff ms" .
.
.
.TP
.B "Format and layout"
By setting registers and strings,
you can change your document's
margins, spacing, headers and footers, footnotes,
and the base point size for the text.
.
See subsection \[lq]Document control settings\[rq] below.
.
.
.TP
.B Document description
A document description consists of any of:
a title,
one or more authors' names and affiliated institutions,
an abstract, and a date or other identifier.
.
See subsection \[lq]Document description macros\[rq] below.
.
.
.TP
.B "Body"
The main matter of your document follows its description
(if any).
.
It consists of paragraphs, headings, and lists.
.
.TP
.B "Table of contents"
Longer documents usually include a table of contents,
which you can add by placing the
.B TC
macro at the end of your document.
.
.
.\" ====================================================================
.SS "Document control settings"
.\" ====================================================================
.
The following tables list the document control registers and strings.
.
For the sake of consistency,
set parameters related to margins at the beginning of your document,
or just after the
.B RP
macro.
.
.
.LP
For entries marked \[lq]special\[rq] in the \[lq]Effective\[rq] column,
see the discussion in the applicable section below.
.
.
.LP
.TS
cb    s  s  s
cb   cb cb cb
lfCR lx  l  lfCR.
Margin settings
Parameter	Definition	Effective	Default
_
\[rs]n[PO]	Page offset (left margin)	next page	1i
\[rs]n[LL]	Line length	next paragraph	6i
\[rs]n[LT]	Header/footer length	next paragraph	6i
\[rs]n[HM]	Top (header) margin	next page	1i
\[rs]n[FM]	Bottom (footer) margin	next page	1i
_
.TE
.
.LP
.TS
cb   s  s  s
cb   cb cb cb
lfCR lx l  lfCR.
Text settings
Parameter	Definition	Effective	Default
_
\[rs]n[PS]	Point size	next paragraph	10p
\[rs]n[VS]	Line spacing (leading)	next paragraph	12p
\[rs]n[HY]	Hyphenation mode	next paragraph	6
\[rs]*[FAM]	Font family	next paragraph	T
_
.TE
.
.
.LP
.TS
cb   s  s  s
cb   cb cb cb
lfCR lx l  lfCR.
Paragraph settings
Parameter	Definition	Effective	Default
_
\[rs]n[PI]	Initial indent	next paragraph	5n
\[rs]n[PD]	Space between paragraphs	next paragraph	0.3v
\[rs]n[QI]	Quoted paragraph indent	next paragraph	5n
\[rs]n[PORPHANS]	# of initial lines kept	next paragraph	1
_
.TE
.
.
.LP
.TS
cb   s  s  s
cb   cb cb cb
lfCR lx l  lfCR.
Heading settings
Parameter	Definition	Effective	Default
_
\[rs]n[PSINCR]	Point size increment	next heading	1p
\[rs]n[GROWPS]	Size increase level limit	next heading	0
\[rs]n[HORPHANS]	# of following lines kept	next heading	1
\[rs]*[SN\-STYLE]	Numbering style (alias)	next heading	\[rs]*[SN\-DOT]
_
.TE
.
.
.LP
.B \[rs]*[SN\-STYLE]
can alternatively be made an alias of
.B \[rs]*[SN\-NO\-DOT]
with the
.B als
request.
.
.
.TS
cb   s  s  s
cb   cb cb cb
lfCR lx  l  lfCR.
Footnote settings
Parameter	Definition	Effective	Default
_
\[rs]n[FI]	Indentation	next footnote	2n
\[rs]n[FF]	Format	next footnote	0
\[rs]n[FPS]	Point size	next footnote	\[rs]n[PS]\-2
\[rs]n[FVS]	Vertical spacing	next footnote	\[rs]n[FPS]+2
\[rs]n[FPD]	Paragraph spacing	next footnote	\[rs]n[PD]/2
\[rs]*[FR]	Line length ratio	special	11/12
_
.TE
.
.
.TS
cb   s  s  s
cb   cb cb cb
lfCR lx  l  lfCR.
Display settings
Parameter	Definition	Effective	Default
_
\[rs]n[DD]	Display distance (spacing)	special	0.5v
\[rs]n[DI]	Display indentation	special	0.5i
_
.TE
.
.
.TS
cb   s  s  s
cb   cb cb cb
lfCR lx  l  lfCR.
Other settings
Parameter	Definition	Effective	Default
_
\[rs]n[MINGW]	Minimum gutter width	next page	2n
_
.TE
.
.
.LP
The \[lq]gutter\[rq] affected by
.B \[rs]n[MINGW]
is the gap between columns in multiple-column page arrangements.
.
.
.\" ====================================================================
.SS "Document description macros"
.\" ====================================================================
.
Define information describing the document by using the macros below in
the order shown;
.B .DA
or
.B .ND
can be called to set the document date
(or other identifier)
at any time before (a) the abstract,
if present,
or (b) its information is required in a header or footer.
.
Use of these macros is optional,
except that
.B .TL
is mandatory if any of
.BR .RP ,
.BR .AU ,
.BR .AI ,
or
.B .AB
is called,
and
.B .AE
is mandatory if
.B .AB
is called.
.
.
.TP
.BR ".RP\~" [ no ]
Use the \[lq]report\[rq]
(AT&T: \[lq]released paper\[rq])
format for your document,
creating a separate cover page.
.
The default arrangement is to print most of the document description
(title,
author names and institutions,
and abstract,
but not the date)
at the top of page\~1.
.
If the optional
.RB \[lq] no \[rq]
argument is given,
.I ms
prints a cover page but does not repeat any of its information on
page\~1
(but see the
.B DA
macro below regarding the date).
.
.
.TP
.B .TL
Specify the document title.
.
.I ms
collects text on input lines following a call to this macro into the
title until reaching an
.BR .AU ,
.BR .AB ,
or heading or paragraph macro call.
.
.
.TP
.B .AU
Specify an author's name.
.
.I ms
collects text on input lines following a call to this macro into the
author's name until reaching an
.BR .AI ,
.BR .AB ,
another
.BR .AU ,
or heading or paragraph macro call.
.
Call it repeatedly to specify multiple authors.
.
.
.TP
.B .AI
Specify the preceding author's institution.
.
An
.B .AU
call is usefully followed by at most one
.B .AI
call;
if there are more,
the last
.B .AI
call controls.
.
.I ms
collects text on input lines following a call to this macro into the
author's institution until reaching an
.BR .AU ,
.BR .AB ,
or heading or paragraph macro call.
.
.
.TP
.B .DA\c
.RI "\~[" x "\~.\|.\|.]"
Print the current date,
or any
.RI arguments\~ x ,
in footers,
and,
if
.B .RP
is also called,
left-aligned after other document description information on the cover
page.
.\" see Savannah #59826
.
.
.TP
.B .ND\c
.RI "\~[" x "\~.\|.\|.]"
Print the current date,
or any
.RI arguments\~ x ,
if
.B .RP
is also called,
left-aligned after other document description information on the cover
page,
but not in footers.
.
.
.TP
.BR ".AB " [ no ]
Begin the abstract.
.
.I ms
collects text on input lines following a call to this macro into the
abstract until reaching an
.B .AE
call.
.
By default,
.I ms
places the word \[lq]ABSTRACT\[rq] centered and in italics above the
text of the abstract.
.
The optional argument
.RB \[lq] no \[rq]
suppresses this heading.
.
.
.TP
.B .AE
End the abstract.
.
.
.\" ====================================================================
.SS Paragraphs
.\" ====================================================================
.
Several paragraph types are available,
differing in how indentation is
applied:
to left,
right,
or both margins;
to the first output line of the paragraph,
all output lines,
or all but the first.
.
All paragraphing macro calls cause the insertion of vertical space in
the amount stored in the
.B PD
register,
except at page or column breaks.
.
.
.PP
The
.B PORPHANS
register defines the minimum number of initial lines of any paragraph
that must be kept together to avoid orphaned lines at the bottom of a
page.
.
If a new paragraph is started close to the bottom of a page,
and there is insufficient space to accommodate
.B \[rs]n[PORPHANS]
lines before an automatic page break,
then a page break is forced before the start of the paragraph.
.
This is a GNU extension.
.
.
.TP
.B .LP
Set a paragraph without any (additional) indentation.
.
.
.TP
.B .PP
Set a paragraph with a first-line left indentation in the amount stored
in the
.B PI
register.
.
.
.TP
.B .IP\c
.RI \~[ marker \~[ width ]]
Set a paragraph with a left indentation.
.
The optional
.I marker
is not indented and is empty by default.
.
.I width
overrides the default indentation amount of
.BR \[rs]n[PI] ;
its default unit is
.RB \[lq] n \[rq].
.
Once specified,
.I width
applies to further
.B .IP
calls until specified again or a heading or different paragraphing macro
is called.
.
.
.TP
.B .QP
Set a paragraph indented from both left and right margins by
.BR \[rs]n[QI] .
.
This macro and register are Berkeley extensions.
.
.
.TP
.B .QS
.TQ
.B .QE
Begin
.RB ( QS )
and end
.RB ( QE )
a region where each paragraph is indented from both margins by
.BR \[rs]n[QI] .
.
The text between
.B .QS
and
.B .QE
can be structured further by use of other paragraphing macros.
.
These macros are GNU extensions.
.
.
.TP
.B .XP
Set an \[lq]exdented\[rq] paragraph\[em]one with a left indentation of
.B \[rs]n[PI]
on every line
.I except
the first
(also known as a hanging indent).
.
This is a Berkeley extension.
.
.
.\" ====================================================================
.SS Headings
.\" ====================================================================
.
Use headings to create a hierarchical structure for your document.
.
The
.I ms
macros print headings in
.B bold
using the same font family and,
by default,
point size as the body text.
.
Numbered and unnumbered headings are available.
.
Text lines after heading macros are treated as part of the heading,
rendered on the same output line in the same style.
.
.
.TP
.BI .NH\~ level
Numbered heading.
.
The
.I level
argument instructs
.I ms
to number heading in the form
.IR a . b . c .\|.\|.,
to any depth desired,
with the numbering of each level increasing automatically and being
reset when a more significant level is increased.
.
.RB \[lq] 1 \[rq]\~is
the most significant or coarsest division of the document.
.
Only nonzero values are output.
.
If you specify heading levels with a gap in an ascending sequence,
such as by invoking
.RB \[lq] ".NH\~3" \[rq]
after
.RB \[lq] ".NH\~1" \[rq],
.I groff ms
emits a warning on the standard error stream.
.
.
.TP
.BI ".NH S\~" heading-level-index\~\c
\&.\|.\|.
Alternatively,
a first argument
.RB of\~\[lq] S \[rq]
can be given,
followed by integral arguments to number the levels of the heading
explicitly.
.
Further automatic numbering,
if used,
resumes using the specified heading level indices as their predecessors.
.
This feature is a GNU extension.
.
.
.PP
After invocation of
.BR .NH ,
the assigned number is made available in the strings
.B SN\-DOT
(as it appears in a printed heading with default formatting,
followed by a terminating period)
and
.B SN\-NO\-DOT
(with the terminating period omitted).
.
These are GNU extensions.
.
.
.PP
You can control the style used to print numbered headings by defining an
appropriate alias for the string
.BR SN\-STYLE .
.
By default,
.B \[rs]*[SN\-STYLE]
is aliased to
.BR \[rs]*[SN\-DOT] .
.
If you prefer to omit the terminating period from numbers appearing in
numbered headings,
you may alias it to
.BR \[rs]*[SN\-NO\-DOT] .
.
Any such change in numbering style becomes effective from the next use
of
.BR .NH ,
following redefinition of the alias for
.BR \[rs]*[SN\-STYLE] .
.
.
.TP
.B .SH\c
.RI " [" level ]
Unnumbered heading.
.
The optional
.I level
argument is a GNU extension indicating the heading level corresponding
to the
.I level
argument of
.BR .NH .
.
It matches the point size at which the heading is printed to that of a
numbered heading at the same level when the
.B \[rs]n[GROWPS]
and
.B \[rs]n[PSINCR]
heading size adjustment mechanism is in effect.
.
.
.PP
The
.B PSINCR
register defines an increment in point size to be applied to headings
at nesting levels more significant
(numerically less)
than the value specified in
.BR \[rs]n[GROWPS] .
.
The value of
.B \[rs]n[PSINCR]
should be specified in points with the
.RB \[lq] p \[rq]
scaling indicator and may include a fractional component.
.
.
.PP
The
.B GROWPS
register defines the heading level at which the point size increment set
by
.B \[rs]n[PSINCR]
becomes effective.
.
Headings more significant
(numerically less)
than that specified by
.B \[rs]n[GROWPS]
are printed at the point size set by
.BR \[rs]n[PS] ;
for each level below the value of
.BR \[rs]n[GROWPS] ,
the point size is increased by
.BR \[rs]n[PSINCR] .
.
Setting
.B \[rs]n[GROWPS]
to a value less than\~2 disables the incremental heading size feature.
.
.
.PP
In other words,
if the
.B GROWPS
register is greater than the
.I level
argument to a
.B .NH
or
.B .SH
call,
the point size of a heading produced by these macros increases by
.B \[rs]n[PSINCR]
units over
.B \[rs]n[PS]
multiplied by the difference between
.I level
and
.BR \[rs]n[GROWPS] .
.
.
.PP
The
.B \[rs]n[HORPHANS]
register operates in conjunction with the
.B NH
and
.B SH
macros to inhibit the printing of orphaned headings at the bottom of a
page;
it specifies the minimum number of lines of the subsequent paragraph
that must be kept on the same page as the heading.
.
If insufficient space remains on the current page to accommodate the
heading and this number of lines of paragraph text,
a page break is forced before the heading is printed.
.
Any display macro or
.IR tbl ,
.IR pic ,
or
.I eqn
region between the heading and the subsequent paragraph suppresses this
grouping.
.
.
.\" ====================================================================
.SS Highlighting
.\" ====================================================================
.
The
.I ms
macros provide a variety of methods to highlight
or emphasize text:
.
.TP
.B .B\c
.RI " [" txt " [" post " [" pre ]]]
Sets its first argument in
.BR "bold type" .
.
If you specify a second argument,
.I groff
prints it in the previous font after
the bold text, with no intervening space
(this allows you to set punctuation after
the highlighted text without highlighting
the punctuation).
.
Similarly, it prints the third argument (if any)
in the previous font
.B before
the first argument.
.
For example,
.RS
.
.IP
\&.B foo ) (
.RE
.
.IP
prints
.RB \[lq]( foo )\[rq].
.
.IP
If you give this macro no arguments,
.I groff
prints all text following in bold until
the next highlighting, paragraph, or heading macro.
.
.TP
.B .R\c
.RI " [" txt " [" post " [" pre ]]]
Sets its first argument in
roman
(or regular)
type.
.
It operates similarly to the
.B B
macro otherwise.
.
.TP
.B .I\c
.RI " [" txt " [" post " [" pre ]]]
Sets its first argument in
.IR "italic type" .
It operates similarly to the
.B B
macro otherwise.
.
.
.TP
.B .BI\c
.RI " [" txt " [" post " [" pre ]]]
Sets its first argument in bold italic type.
.
It operates similarly to the
.B B
macro otherwise.
.
This is a Version\~10 Research Unix extension.
.\" Possibly V9, but definitely not Berkeley.
.
.
.TP
.B .CW\c
.RI " [" txt " [" post " [" pre ]]]
Sets its first argument in a \[lq]constant-width\[rq] (monospaced) roman
typeface.
.
It operates similarly to the
.B B
macro otherwise.
.
This is a Version\~10 Research Unix extension.
.\" Possibly V9, but definitely not Berkeley.
.
.
.TP
.B .BX\c
.RI " [" txt ]
Prints
.I txt
and draws a box around it.
.
On terminal devices,
reverse video is used instead.
.
If you want the argument to contain space,
use non-breaking space escapes of appropriate width
.RB ( \[rs]\[ti] ,
.BR \[rs]\[ha] ,
.BR \[rs]| ,
.BR \[rs]0 ),
or
.BR \[rs]h .
.
.
.TP
.B .UL\c
.RI " [" txt " [" post ]]
Prints its first argument with an underline.
.
If you specify a second argument,
.I groff
prints it in the previous font after the underlined text, with no
intervening space.
.
.TP
.B .LG
Prints all text following in larger type
(2\~points larger than the current point size) until
the next font size, highlighting, paragraph, or heading macro.
.
You can specify this macro multiple times to enlarge the point size as
needed.
.
.TP
.B .SM
Prints all text following in
smaller type
(2\~points smaller than the current point size) until
the next type size, highlighting, paragraph, or heading macro.
.
You can specify this macro multiple times to reduce the point size as
needed.
.
.TP
.B .NL
Prints all text following in
the normal point size
(that is, the value of the
.B PS
register).
.
.
.TP
.BI \[rs]*{ text \[rs]*}
Print the enclosed
.I text
as a superscript.
.
.
.TP
.BI \[rs]*< text \[rs]*>
Print the enclosed
.I text
as a subscript.
.
.
.\" ====================================================================
.SS "Indented regions"
.\" ====================================================================
.
You may need to indent a region of text while still wrapping and
filling.
.
.
.TP
.B .RS
Begin a region indented by
.BR \[rs]n[PI] ,
affecting the placement of headings,
paragraphs,
and displays.
.
.
.TP
.B .RE
End the most recent indented region.
.
.
.PP
You can use
.BR .RS / .RE
regions to line up text under hanging and indented paragraphs.
.
For example,
you may wish to nest lists.
.
.
.\" ====================================================================
.SS "Tab stops"
.\" ====================================================================
.
Use the
.B ta
request to set tab stops as needed.
.
Use the
.B TA
macro to reset tabs to the default (every 5n).
.
You can redefine the
.B TA
macro to create a different set of default tab stops.
.
.
.\" ====================================================================
.SS "Displays and keeps"
.\" ====================================================================
.
Use displays to show text-based examples or figures
(such as code listings).
.
Displays turn off filling, so lines of code can be displayed as-is
without inserting
.B br
requests in between each line.
.
Displays can be
.I kept
on a single page, or allowed to break across pages.
.
The following table shows the display types available.
.RS
.ne 11
.TS
cb   s    cbt
cb   cb   ^
lfCR lfCR lx.
Display macro	Type of display
With keep	No keep
_
\&.DS L	\&.LD	Left-justified.
\&.DS I [\,\fIindent\/\fP]	\&.ID	T{
Indented (default indent in the \fBDI\fP register).
T}
\&.DS B	\&.BD	T{
Block-centered (left-justified, longest line centered).
T}
\&.DS C	\&.CD	Centered.
\&.DS R	\&.RD	Right-justified.
_
.TE
.RE
.
.LP
Use the
.B DE
macro to end any display type.
.
.
.PP
The distance stored in
.B \[rs]n[DD]
is inserted before and after each pair of display macros.
.
This is a Berkeley extension.
.
.
.PP
The
.B \[rs]n[DI]
indentation is applied to only to displays created with
.RB \[lq] ".DS I" \[rq]
and
.BR .ID .
.
Changes take effect at the next display boundary.
.
This is a GNU extension.
.
.
.PP
To
.I keep
text together on a page,
such as
a paragraph that refers to a table (or list, or other item)
immediately following, use the
.B KS
and
.B KE
macros.
.
The
.B KS
macro begins a block of text to be kept on a single page,
and the
.B KE
macro ends the block.
.
.
.PP
You can specify a
.I floating keep
using the
.B KF
and
.B KE
macros.
.
If the keep cannot fit on the current page,
.I groff
holds the contents of the keep and allows text following
the keep (in the source file) to fill in the remainder of
the current page.
.
When the page breaks,
whether by an explicit
.B bp
request or by reaching the end of the page,
.I groff
prints the floating keep at the top of the new page.
.
This is useful for printing large graphics or tables
that do not need to appear exactly where specified.
.
.
.PP
Use the following macros to draw a box around a region of the page.
.
.
.TS
box;
cb cb
lf(CR) lx .
Macro	Description
_
\&.B1	Begin a keep with a box drawn around it.
\&.B2	End boxed keep.
.TE
.
.
.PP
These macros cause line breaks;
if you need to box a word or phrase within a line,
see the
.B BX
macro in section \[lq]Highlighting\[rq] above.
.
.
.\" ====================================================================
.SS "Tables, figures, equations, and references"
.\" ====================================================================
.
The
.I ms
macros support the standard
.I groff
preprocessors:
.IR \%@g@tbl ,
.IR \%@g@pic ,
.IR \%@g@eqn ,
and
.IR \%@g@refer (@MAN1EXT@).
.
The
.B \[rs]n[DD]
distance is also applied to regions of the document preprocessed with
.IR \%@g@eqn (@MAN1EXT@),
.IR \%@g@pic (@MAN1EXT@),
and
.IR \%@g@tbl (@MAN1EXT@).
.
Mark text meant for preprocessors by enclosing it in pairs of tags as
follows.
.
.
.TP
.BR .TS " [" H "] and " .TE
Denote a table to be processed by the
.I tbl
preprocessor.
.
The optional
.BR H "\~argument"
instructs
.I groff
to create a running header with the information
up to the
.B TH
macro.
.
.I groff
prints the header at the beginning of the table;
if the table runs onto another page,
.I groff
prints the header on the next page as well.
.
.TP
.BR .PS " and " .PE
Denote a graphic to be processed by the
.I pic
preprocessor.
.
You can create a
.I pic
file by hand, using the
AT&T
.I pic
manual available on the Web as a reference,
or by using a graphics program such as
.IR xfig .
.
.TP
.B .EQ\c
.RI " [" align "] and "\c
.B .EN
Denote an equation to be processed by the
.I eqn
preprocessor.
.
The optional
.I align
argument can be
.BR C ,
.BR L ,
or\~\c
.B I
to center (the default), left-justify, or indent
the equation, respectively.
.
.TP
.BR .[ " and " .]
Denote a reference to be processed by the
.I refer
preprocessor.
.
The GNU
.IR \%@g@refer (@MAN1EXT@)
manual page provides a comprehensive reference
to the preprocessor and the format of the
bibliographic database.
.
.
.PP
Attempting to place a multi-page table inside a keep can lead to
unpleasant results,
particularly if the
.I tbl
.RB \[lq] allbox \[rq]
option is used.
.
.
.\" ====================================================================
.SS Footnotes
.\" ====================================================================
.
A footnote is typically anchored to a place in the text with a
.IR marker ,
which is a small integer,
a symbol,
or arbitrary user-specified text.
.
The footnote text is set at the nearest available \[lq]foot\[rq],
or bottom,
of a text column or page.
.
.
.PP
Automatic numbering of footnotes is available.
.
The
.B *
string places such a footnote marker in the text.
.
Each time this string is interpolated,
the number it produces increments by one.
.
Automatic footnote numbers start at 1.
.
This is a Berkeley extension.
.
.
.TP
.B .FS\c
.RI \~[ marker ]
Begin a footnote.
.
A
.I marker
argument is placed at the beginning of the footnote text.
.
If
.I marker
is omitted,
the next pending automatic footnote number enqueued by interpolation of
the
.B *
string is used,
and if none exists,
nothing is prefixed.
.
.
.TP
.B .FE
End footnote text.
.
.
The
.B FF
register controls the formatting of automatically numbered footnotes,
and those for which
.B .FS
is given a marker argument,
at the bottom of a column or page as follows.
.
.
.RS
.TP
0
Set an automatic number as a superscript
(on typesetter devices)
or surrounded by square brackets
(on terminals).
.
The footnote paragraph is indented if there is an
.B .FS
argument or an automatic number.
.
This is the default.
.
.
.TP
1
Like
.BR 0 ,
but set the marker as regular text,
and follow an automatic number with a period.
.
.
.TP
2
Like
.BR 1 ,
but without indentation.
.
.
.TP
3
Like
.BR 1 ,
but set the footnote paragraph with the marker hanging.
.RE
.
.
.\" ====================================================================
.SS "Headers and footers"
.\" ====================================================================
.
There are three ways to define headers and footers:
.
.IP \[bu] 3n
Use the strings
.BR LH ,
.BR CH ,
and
.B RH
to set the left, center, and right headers.
Use
.BR LF ,
.BR CF ,
and
.B RF
to set the left, center, and right footers.
.
The string-setting approach works best for documents that do not
distinguish between odd and even pages.
.
.IP \[bu]
Use the
.B OH
and
.B EH
macros to define headers for the odd and even pages,
and
.B OF
and
.B EF
macros to define footers for the odd and even pages.
.
This is more flexible than defining the individual strings.
.
The syntax for these macros is as follows:
.RS
.
.IP
.BI . XX " \[aq]" left \[aq] center \[aq] right \[aq]
.RE
.
.IP
where
.I XX
is one of the foregoing four macros and each of
.IR left ,
.IR center ,
and
.I right
is text of your choice.
.
You can replace the quote (\[aq]) marks with any character not
appearing in the header or footer text.
.
.
.IP \[bu]
You can redefine the
.B PT
and
.B BT
macros to change the behavior of
the header and footer, respectively.
.
The header process also calls the (undefined)
.B HD
macro after
.BR PT ;
you can define this macro if you need additional processing
after printing the header
(for example, to draw a line below the header).
.
.
.TP
.B .P1
Print the header on page\~1.
.
By default,
no header is printed on that page.
.
This is a Berkeley extension.
.
.
.\" ====================================================================
.SS Margins
.\" ====================================================================
.
Control margins using registers.
.
These are summarized in the \[lq]Margin settings\[rq] table in
subsection \[lq]Document control settings\[rq] above.
.
There is no explicit right margin setting;
the combination of page offset
.B \[rs]n[PO]
and line length
.B \[rs]n[LL]
provides the information necessary to derive the right margin.
.
.
.\" ====================================================================
.SS "Multiple columns"
.\" ====================================================================
.
The
.I ms
macros can set text in as many columns as will reasonably fit on the
page.
.
The following macros are available.
.
All of them force a page break if a multi-column mode is already set.
.
However, if the current mode is single-column, starting a multi-column
mode does
.I not
force a page break.
.
.TP
.B .1C
Single-column mode.
.
.TP
.B .2C
Two-column mode.
.
.TP
.B .MC\c
.RI " [" column-width " [" gutter-width ]]
Multi-column mode.
.
If you specify no arguments, it is equivalent to the
.B 2C
macro.
.
Otherwise,
.I column-width
is the width of each column and
.I gutter-width
is the space between columns.
.
The
.B MINGW
register is the default gutter width.
.
.
.\" ====================================================================
.SS "Creating a table of contents"
.\" ====================================================================
.
Wrap text that you want to appear in the table of contents in
.B XS
and
.B XE
macros.
.
Use the
.B TC
macro to print the table of contents at the end of the document,
resetting the page number to\~\c
.B i
(Roman numeral\~1).
.
.
.PP
You can manually create a table of contents
by specifying a page number as the first argument to
.BR XS .
.
Add subsequent entries using the
.B XA
macro.
.
For example:
.RS
.
.PP
.ne 8
.EX
\&.XS 1
Introduction
\&.XA 2
A Brief History of the Universe
\&.XA 729
Details of Galactic Formation
\&.\|.\|.
\&.XE
.EE
.RE
.
.
.LP
Use the
.B PX
macro to print a manually-generated table of contents
without resetting the page number.
.
.
.PP
If you give the argument
.RB \[lq] no \[rq]
to either
.B PX
or
.BR TC ,
.I groff
suppresses printing the title
specified by the
.B \[rs]*[TOC]
string.
.
.
.\" ====================================================================
.SS "Fractional point sizes"
.\" ====================================================================
.
Traditionally, the
.I ms
macros only support integer values for the document's font size
and vertical spacing.
.
To overcome this restriction, values larger than or equal to 1000 are
taken as fractional values, multiplied by 1000.
.
For example, \[oq].nr\~PS\~10250\[cq] sets the font size to 10.25
points.
.
.
.LP
The following four registers accept fractional point sizes:
.BR PS ,
.BR VS ,
.BR FPS ,
and
.BR FVS .
.
.
.\" ====================================================================
.SH "Differences from AT&T \f[I]ms\f[]"
.\" ====================================================================
.
The
.I groff ms
macros are a complete re-implementation,
using no original AT&T code.
.
Since they take advantage of the extended features in
.IR groff ,
they cannot be used with AT&T
.IR troff .
.
Other differences include:
.
.
.IP \[bu] 3n
The internals of
.I groff ms
differ from the internals of AT&T
.IR ms .
.
Documents that depend upon implementation details of AT&T
.I ms
may not format properly with
.IR "groff ms" .
.
Such details include macros whose function was not documented in the
AT&T
.I ms
manual
(\[lq]Typing Documents on the UNIX System: Using the \-ms Macros with
Troff and Nroff\[rq],
M.\& E.\& Lesk,
Bell Laboratories,
1978).
.\" TODO: Use refer(1)?
.\" XXX: We support RT anyway; maybe we should stop?
.
.
.IP \[bu]
The error-handling policy of
.I groff ms
is to detect and report errors,
rather than silently to ignore them.
.
.
.IP \[bu]
Berkeley localisms, in particular the
.B TM
and
.B CT
macros,
are not implemented.
.
.
.IP \[bu]
(Version\~10
.\" possibly V9
Research Unix supported a pair of
.B P1
and
.B P2
macros for setting code examples;
.I groff ms
does not.)
.
.
.IP \[bu]
.I groff ms
does not work in
.IR \%@g@troff 's
compatibility mode.
.
If loaded when that mode is enabled,
it aborts processing with a diagnostic message.
.
.
.IP \[bu]
Multiple line spacing is not supported
(use a larger vertical spacing instead).
.
.
.IP \[bu]
.I groff ms
uses the same header and footer defaults in both
.B nroff
and
.B troff
modes
as AT&T
.I ms
does in
.B troff
mode;
AT&T's default in
.B nroff
mode is to put the date,
in U.S.\& traditional format
(e.g.,
\[lq]January 1, 2021\[rq]),
in the center footer
(the
.B CF
string).
.
.
.IP \[bu]
The AT&T
.I ms
manual describes
.B CW
and
.B GW
registers that can be used to control the column width and gutter width,
respectively.
.
These registers are not used in
.IR "groff ms" .
.
(However,
see
.B MINGW
in the \[lq]Other Settings\[rq] table of subsection \[lq]Document
control settings\[rq],
above.
.
.
.IP \[bu]
Macros that cause a reset
(paragraphs, headings, etc.\&)
may change the indent.
.
Macros that change the indent do not increment or decrement the
indent, but rather set it absolutely.
.
This can cause problems for documents that define additional macros of
their own.
.
The solution is to use not the
.B in
request but instead the
.B RS
and
.B RE
macros.
.
.
.IP \[bu]
To make
.I groff ms
use the default page offset
(which also specifies the left margin),
the
.B PO
register must stay undefined until the first
.B ms
macro is called.
.
This implies that
.B PO
should not be used early in the document,
unless it is changed also:
accessing an undefined register automatically defines it.
.
.
.IP \[bu]
Displays are left-adjusted by default,
not indented.
.
In AT&T
.IR ms ,
.B .DS
is synonymous with
.RB \[lq] ".DS I" \[rq];
in
.IR "groff ms" ,
it is synonymous with
.RB \[lq] ".DS L" \[rq].
.
.
.IP \[bu]
Right-adjusted displays are available.
.
The AT&T
.I ms
manual observes that \[lq]it is tempting to assume that \[oq].DS R\[cq]
will right adjust lines,
but it doesn't work\[rq].
.
In
.IR "groff ms" ,
it does.
.
.
.IP \[bu]
.I groff ms
handles
.RB \[lq] S \[rq]
as the first argument to the
.B NH
macro specially,
allowing explicit numbering of headings.
.
.
.IP \[bu]
.I groff ms
supports the
.B PN
register,
but it is not necessary;
you can access the page number via the usual
.B %
register and use the
.B af
request to assign a different format to it if desired.
.
(If you redefine the
.I ms
.B PT
macro \" I wouldn't mention that, but Lesk 1978 encourages doing so. :-/
and desire special treatment of certain page numbers\[em]like
.RB \[lq] 1 \[rq]\[em]you
may need to handle a non-decimal page number format,
as
.IR "groff ms" 's
.B .PT
does;
see the macro package source.
.
.I groff ms
aliases the
.B PN
register to
.BR % .)
.
.
.IP \[bu]
The register
.B GS
is set to\~1 by the
.I groff ms
macros,
but is not used by the AT&T
.I ms
macros.
.
Documents that need to determine whether they are being formatted with
.I groff ms
or another implementation should use this register.
.
.
.\" ====================================================================
.SS "Localization strings"
.\" ====================================================================
.
You can redefine the following strings to adapt the
.I groff ms
macros to languages other than English.
.
.RS
.TS
cb   cb
lfCR lfCR.
String	Default
_
REFERENCES	References
ABSTRACT	\[rs]f[I]ABSTRACT\[rs]f[]
TOC	Table of Contents
MONTH1	January
MONTH2	February
MONTH3	March
MONTH4	April
MONTH5	May
MONTH6	June
MONTH7	July
MONTH8	August
MONTH9	September
MONTH10	October
MONTH11	November
MONTH12	December
_
.TE
.RE
.
The default for
.B ABSTRACT
includes font style escapes to set the word in italics.
.
.
.PP
The
.B \[rs]*\-
string produces an em dash\[em]like this.
.
.
.PP
Use
.B \[rs]*Q
and
.B \[rs]*U
to get a left and right typographer's quote,
respectively, in
.I troff
(and plain quotes in
.IR nroff ).
.
.
.\" ====================================================================
.SS "Text settings"
.\" ====================================================================
.
The
.B FAM
string sets the font family for body text.
.
If this string is undefined at initialization,
it is set to
.RB \[lq] T \[rq]
(Times).
.
Setting
.B \[rs]*[FAM]
before the first call of a sectioning,
paragraphing,
or (non-date) document description macro also applies it to headers,
footers,
and footnotes
(as well as the body text).
.
.
.LP
The point size, vertical spacing, and inter-paragraph spacing for
footnotes are controlled by the registers
.BR FPS ,
.BR FVS ,
and
.BR FPD ;
at initialization these are set to
.BR \[rs]n(PS\-2 ,
.BR \[rs]n[FPS]+2 ,
and
.BR \[rs]n(PD/2 ,
respectively.
.
If any of these registers are defined before initialization,
the initialization macro does not change them.
.
.
.LP
The hyphenation flags (as set by the
.B hy
request) are set from the
.B HY
register;
the default is\~6.
.
.
.PP
Improved accent marks
(as originally defined in Berkeley's
.I ms
version)
are available by specifying the
.B AM
macro at the beginning of your document.
.
You can place an accent over most characters by specifying the string
defining the accent directly after the character.
.
For example,
.B n\[rs]*\[ti]
produces an n with a tilde over it.
.
.
.\" ====================================================================
.SH "Naming conventions"
.\" ====================================================================
.
The following conventions are used for names of macros,
strings,
and registers.
.
External names available to documents that use the
.I groff ms
macros contain only uppercase letters and digits.
.
.
.LP
Internally the macros are divided into modules;
naming conventions are as follows:
.
.IP \[bu] 3n
Names used only within one module are of the form
.IB \%module * name\c
\&.
.
.IP \[bu]
Names used outside the module in which they are defined are of the form
.IB \%module @ name\c
\&.
.
.IP \[bu]
Names associated with a particular environment are of the form
.IB \%environment : name\c
\&;
these are used only within the
.B par
module.
.
.IP \[bu]
.I name
does not have a module prefix.
.
.IP \[bu]
Constructed names used to implement arrays are of the form
.IB \%array ! index\c
\&.
.
.
.PP
Thus the
.I groff ms
macros reserve the following names:
.
.IP \[bu] 3n
Names containing the characters
.BR * ,
.BR @ ,
and\~\c
.BR : .
.
.IP \[bu]
Names containing only uppercase letters and digits.
.
.
.\" ====================================================================
.SH Files
.\" ====================================================================
.
.TP
.I \%@MACRODIR@/\:s\:.tmac
.I groff
implementation of manuscript macros.
.
.
.TP
.I \%@MACRODIR@/\:ms\:.tmac
Wrapper to load
.IR s.tmac .
.
.
.
.\" ====================================================================
.SH Authors
.\" ====================================================================
.
The GNU version of the
.I ms
macro package was written by James Clark and contributors.
.
This document was (re-)written by
.MT lkollar@\:despammed\:.com
Larry Kollar
.ME .
.
.
.\" ====================================================================
.SH "See also"
.\" ====================================================================
.
.
A manual is available in source and rendered form.
.
On your system,
it may be compressed and/or available in additional formats.
.
.
.TP
.I \%@DOCDIR@/\:ms\:.ms
.TQ
.I \%@DOCDIR@/\:ms\:.ps
\[lq]Using
.I groff
with the
.I ms
Macro Package\[rq];
Larry Kollar.
.
.
.PP
.IR "Groff: The GNU Implementation of troff" ,
by Trent A.\& Fisher and Werner Lemberg
.
.
.PP
.IR groff (@MAN1EXT@),
.IR \%@g@troff (@MAN1EXT@),
.IR \%@g@tbl (@MAN1EXT@),
.IR \%@g@pic (@MAN1EXT@),
.IR \%@g@eqn (@MAN1EXT@),
.IR \%@g@refer (@MAN1EXT@)
.
.
.\" Restore compatibility mode (for, e.g., Solaris 10/11).
.cp \n[*groff_groff_ms_7_man_C]
.
.
.\" Local Variables:
.\" fill-column: 72
.\" mode: nroff
.\" End:
.\" vim: set filetype=groff textwidth=72:
