.TH groff_tmac @MAN5EXT@ "@MDATE@" "groff @VERSION@"
.SH Name
groff_tmac \- macro files in the GNU roff typesetting system
.
.
.\" ====================================================================
.\" Legal Terms
.\" ====================================================================
.\"
.\" Copyright (C) 2000-2021 Free Software Foundation, Inc.
.\"
.\" This file is part of groff, the GNU roff typesetting system.
.\"
.\" Permission is granted to copy, distribute and/or modify this
.\" document under the terms of the GNU Free Documentation License,
.\" Version 1.3 or any later version published by the Free Software
.\" Foundation; with no Invariant Sections, with no Front-Cover Texts,
.\" and with no Back-Cover Texts.
.\"
.\" A copy of the Free Documentation License is included as a file
.\" called FDL in the main directory of the groff source package.
.
.
.\" Save and disable compatibility mode (for, e.g., Solaris 10/11).
.do nr *groff_groff_tmac_5_man_C \n[.cp]
.cp 0
.
.
.\" ====================================================================
.SH Description
.\" ====================================================================
.
Definitions of macros,
strings,
and registers for use in a
.IR roff (@MAN7EXT@)
document can be collected into
.IR "macro files" ,
.I roff
input files designed to produce no output themselves but instead ease
the preparation of other
.I roff
documents.
.
There is no syntactical difference between a macro file and any other
.I roff
document;
only its purpose distinguishes it.
.
When a macro file is installed at a standard location and suitable for
use by a general audience,
it is often termed a
.IR "macro package" .
.
Macro packages can be loaded by supplying the
.B \-m
option to
.IR groff (@MAN1EXT@)
or
.IR \%@g@troff (@MAN1EXT@).
.
Alternatively,
a
.I groff
document wishing to use a macro package can load it with the
.B mso
(\[lq]macro source\[rq]) request.
.
.
.P
Each macro package stores its macro,
string,
and register definitions in one or more
.I tmac
files.
.
This name originated in early Unix culture as an abbreviation of
.RI \[lq] troff \" generic
macros\[rq].
.
.
.P
A macro package must be named
.RI name .tmac
and be placed in a
.RI \[lq] tmac
directory\[rq] to be loadable with the
.B \-m
option.
.
Section \[lq]Environment\[rq] of
.IR \%@g@troff (@MAN1EXT@)
lists these directories.
.
Like any other
.I roff
document,
a macro package can use the
.RB \[lq] so \[rq]
request (\[lq]source\[rq]) to load further files relative to its own
location.
.
.
.\" ====================================================================
.SH "Macro packages"
.\" ====================================================================
.
Macro packages come in two varieties;
those which assume responsibility for page layout and other critical
functions
(\[lq]major\[rq] or \[lq]full-service\[rq])
and those which do not
(\[lq]supplemental\[rq] or \[lq]auxiliary\[rq]).
.
GNU
.I roff
provides most major macro packages found in AT&T and BSD Unix systems,
an additional full-service package,
and many supplemental packages.
.
Multiple full-service macro packages cannot be used by the same
document.
.
Auxiliary packages can generally be freely combined,
though attention to their use of the
.I groff
language name spaces for identifiers
(particularly registers,
macros,
strings,
and diversions)
should be paid.
.
Name space management was a significant challenge in AT&T
.IR troff ;
.IR groff 's
support for arbitrarily long identifiers affords few excuses for name
collisions,
apart from attempts at compatibility with the demands of historical
documents.
.
.
.\" ====================================================================
.SS "Man pages"
.\" ====================================================================
.
.TP
.I an
.TQ
.I man
.I an
is used to compose man pages in the format originating in Version\~7
Unix (1979).
.
It has a small macro interface and is widely used;
see
.IR groff_man (@MAN7EXT@).
.
.
.TP
.I doc
.TQ
.I mdoc
.I doc
is used to compose man pages in the format originating in 4.3BSD-Reno
(1990).
.
It provides many more features than
.IR an ,
but is also larger,
more complex,
and not as widely adopted;
see
.IR groff_mdoc (@MAN7EXT@).
.
.
.P
Because readers of man pages often do not know in advance which macros
are used to format a given document,
a wrapper is available.
.
.
.TP
.I \%andoc
.TQ
.I mandoc
This macro file,
specific to
.IR groff ,
recognizes whether a document uses
.I man
or
.I mdoc
format and loads the corresponding macro package.
.
Multiple man pages,
in either format,
can be handled;
.I \%andoc
reloads each macro package as necessary.
.
.
.\" ====================================================================
.SS "Full-service packages"
.\" ====================================================================
.
The packages in this section provide a complete set of macros for
writing documents of any kind, up to whole books.
.
They are similar in functionality; it is a matter of taste which one
to use.
.
.
.TP
.I me
The classical
.I me
macro package; see
.IR groff_me (@MAN7EXT@).
.
.
.TP
.I mm
The semi-classical
.I mm
macro package; see
.IR groff_mm (@MAN7EXT@).
.
.
.TP
.I mom
The
.I mom
macro package, only available in groff.
.
As this was not based on other packages, it was freely designed as
quite a nice, modern macro package.
.
See
.IR groff_mom (@MAN7EXT@).
.
.
.TP
.I ms
The classical
.I ms
macro package; see
.IR groff_ms (@MAN7EXT@).
.
.
.\" ====================================================================
.SS "Localization packages"
.\" ====================================================================
.
.P
For Western languages,
the localization file sets the hyphenation mode and loads hyphenation
patterns and exceptions.
.
Localization files can also adjust the date format and provide
translations of strings used by some of the full-service macro packages;
alter the input encoding
(see the next section);
and change the amount of inter-sentence space.
.
By default,
.I troffrc
loads the localization file for English.
.
.
.P
As of
.I groff
1.23.0,
the following localization files exist.
.
.
.TP
.I cs
Czech;
localizes
.IR me ,
.IR mm ,
.IR mom ,
and
.IR ms .
.
Sets the input encoding to Latin-2 by loading
.IR latin2.tmac .
.
.
.TP
.I de
.TQ
.I den
German;
localizes
.IR me ,
.IR mm ,
.IR mom ,
and
.IR ms .
.
Sets the input encoding to Latin-1 by loading
.IR latin1.tmac .
.
.
.IP
.I de.tmac
selects hyphenation patterns for traditional orthography,
and
.I den.tmac
does the same for the new orthography
(\[lq]Recht\%schreib\%reform\[rq]).
.
.
.TP
.I en
English.
.
.
.TP
.I fr
French;
localizes
.IR me ,
.IR mm ,
.IR mom ,
and
.IR ms .
.
Sets the input encoding to Latin-9 by loading
.IR latin9.tmac .
.
.
.TP
.I it
Italian;
localizes
.IR me ,
.IR mm ,
.IR mom ,
and
.IR ms .
.
.
.TP
.I ja
Japanese.
.
.
.TP
.I sv
Swedish;
localizes
.IR me ,
.IR mm ,
.IR mom ,
and
.IR ms .
.
Sets the input encoding to Latin-1 by loading
.IR latin1.tmac .
.
Some of the localization of the
.I mm
package is handled separately;
see
.IR groff_mmse (@MAN7EXT@).
.
.
.TP
.I zh
Chinese.
.
.
.\" ====================================================================
.SS "Input encodings"
.\" ====================================================================
.
.TP
.I latin1
.TQ
.I latin2
.TQ
.I latin5
.TQ
.I latin9
Various input encodings supported directly by groff.
.
Normally, this macro is loaded at the very beginning of a document or
specified as the first macro argument on the command line.
.
.I groff
loads latin1 by default at start-up.
.
These macro packages don't work on EBCDIC hosts.
.
.
.TP
.I cp1047
Encoding support for EBCDIC.
.
On those platforms it is loaded automatically at start-up.
.
Due to different character ranges used in
.I groff
it doesn't work on architectures which are based on ASCII.
.
.
.P
Some input encoding characters may not be available for a particular
output device.
.
For example, saying
.
.P
.EX
groff \-Tlatin1 \-mlatin9 ...
.EE
.
.P
fails if you use the Euro character in the input.
.
Usually, this limitation is present only for drivers which have a
limited set of output glyphs
.RB ( ascii ,
.BR latin1 );
for other drivers it is usually sufficient to install proper
fonts which contain the necessary glyphs.
.
.
.\" ====================================================================
.SS "Auxiliary packages"
.\" ====================================================================
.
The macro packages in this section are not intended for stand-alone
use,
but can add functionality to any other macro package or to plain
(or \[lq]raw\[rq])
.I groff
documents.
.
.
.TP
.I 62bit
Provides macros for addition, multiplication, and division of 62-bit
integers (allowing safe multiplication of 31-bit integers, for example).
.
.
.TP
.I ec
Switch to the EC and TC font families.
.
To be used with
.IR \%grodvi (@MAN1EXT@)
\[em] this man page also gives more details of how to use it.
.
.
.TP
.I hdtbl
The Heidelberger table macros, contributed by Joachim Walsdorff, allow
the generation of tables through a syntax similar to the HTML table
model.
.
Note that
.I hdtbl
is a macro package, not a preprocessor like
.IR tbl (@MAN1EXT@).
.
.I hdtbl
works only with the
.B ps
and
.B pdf
output drivers.
.
See
.IR groff_hdtbl (@MAN7EXT@).
.
.
.TP
.I papersize
This macro file is normally loaded at start-up by the
.I troffrc
file.
.
It provides an interface to set the paper size on the command line with
the option
.BI "\-d \%paper=" size
or
.IR \%@g@troff .
.
Possible values for
.I size
are the ISO and DIN formats
\[lq]A0\[en]A6\[rq],
\[lq]B0\[en]B6\[rq],
\[lq]C0\[en]C6\[rq],
and
\[lq]D0\[en]D6\[rq];
.\" XXX: src/libs/libgroff/paper.cpp also supports [ABCD]7.
the U.S.\& formats
\[lq]letter\[rq],
\[lq]legal\[rq],
\[lq]tabloid\[rq],
\[lq]ledger\[rq],
\[lq]statement\[rq],
and
\[lq]executive\[rq];
and the envelope formats
\[lq]com10\[rq],
\[lq]monarch\[rq],
and
\[lq]DL\[rq].
.
All formats,
even those for envelopes,
are in portrait orientation,
with their longer dimension as the length.
.
Appending \[lq]l\[rq] (ell) to any of these denotes landscape
orientation instead.
.
An output device typically requires command-line options
.B \-p
and
.B \-l
to override the paper dimensions and orientation,
respectively,
defined in its
.I DESC
file;
see subsection \[lq]Paper sizes\[rq]
of
.IR groff (@MAN1EXT@).
.
.
.TP
.I pdfpic
A single macro is provided in this file,
.BR PDFPIC ,
to include a PDF graphic in a document, i.e., under the output driver
.BR pdf .
.
For all other drivers,
.I pspic
is used.
.
So
.I pdfpic
is an extension of
.IR pspic .
.
This means you can safely replace all
.B PSPIC
with
.BR PDFPIC ;
nothing gets lost by that.
.
The options of
.B PDFPIC
are identical to the
.B PSDIF
options.
.
.
.TP
.I pic
This file provides proper definitions for the macros
.B PS
and
.BR PE ,
needed for the
.IR @g@pic (@MAN1EXT@)
preprocessor.
.
They center each picture.
.
Use it only if your macro package doesn't provide proper
definitions for those two macros (most of them already do).
.
.
.TP
.I pspic
A single macro is provided in this file,
.BR PSPIC ,
to include a PostScript graphic in a document.
.
The
.BR ps ,
.BR dvi ,
.BR html ,
and
.B xhtml
output drivers support inclusion of PS images; for all other drivers
the image is replaced with a hollow rectangle of the same size.
.
This macro file is automatically loaded at start-up by
.B @g@troff
so it isn't necessary to call it explicitly.
.
.IP
Syntax:
.RS
.IP
\&\fB.PSPIC\fP \
[\fB\-L\fP\|\
|\|\fB\-R\fP\|\
|\|\fB\-C\fP\|\
|\|\fB\-I\fP\ \fIn\fP] \
\fI\|file\fP [\fIwidth\fP [\,\fIheight\/\fP]]
.RE
.
.IP
.I file
is the name of the PostScript file;
.I width
and
.I height
give the desired width and height of the image.
.
If neither a
.I width
nor a
.I height
argument is specified, the image's natural width (as given in the
file's bounding box) or the current line length is used as the
width, whatever is smaller.
.
The
.I width
and
.I height
arguments may have scaling indicators attached;
the default scaling indicator is\~\c
.BR i .
.
This macro scales the graphic uniformly
in the x and y\~directions so that it is no more than
.I width
wide
and
.I height
high.
.
Option
.B \-C
centers the graphic horizontally, which is the default.
.
The
.B \-L
and
.B \-R
options left-align and right-align the graphic, respectively.
.
The
.B \-I
option indents the graphic by\~\c
.I n
(default scaling indicator is\~\c
.BR m ).
.
.IP
For use of
.B .PSPIC
within a diversion it is recommended to extend it with the following
code, assuring that the diversion's width completely covers the
image's width.
.
.RS
.IP
.EX
\&.am PSPIC
\&.\ \ vpt 0
\&\[rs]h\[aq](\[rs]\[rs]n[ps-offset]u + \[rs]\[rs]n[ps-deswid]u)\[aq]
\&.\ \ sp \-1
\&.\ \ vpt 1
\&..
.EE
.RE
.
.
.TP
.I ptx
A single macro is provided in this file,
.BR xx ,
for formatting permuted index entries as produced by the GNU
.IR ptx (1)
program.
.
If you need different formatting, copy the macro into your document and
adapt it to your needs.
.
.
.TP
.I rfc1345
defines special character escape sequences based on the glyph mnemonics
specified in RFC 1345 and the digraph table of the text editor Vim.
.
See
.IR groff_rfc1345 (@MAN7EXT@).
.
.
.TP
.I trace
Use this for tracing macro calls.
.
It is only useful for debugging.
.
See
.IR groff_trace (@MAN7EXT@).
.
.
.TP
.I tty\-char
Defines fallback definitions of
.I roff
special characters for terminal devices.
.
These definitions more poorly optically approximate typeset output
compared to those of the
.I tty
file in favor of communicating more semantic information,
which can allow easier processing with critical equipment.
.\" XXX: critical equipment like what?
.
.
.TP
.I www
Additions of elements known from the HTML format, as used in World
Wide Web pages; this includes URL links and mail addresses.
.
See
.IR groff_www (@MAN7EXT@).
.
.
.\" ====================================================================
.SH Naming
.\" ====================================================================
.
Classical roff systems were designed before the conventions of the
modern C
.IR getopt (3)
call evolved, and used a naming scheme for macro packages that looks
odd to modern eyes.
.
Macro packages were always included with the option
.BR \-m ;
when this option was directly followed by its argument without an
intervening space, this looked like a long option preceded by a single
minus \[em] a sensation in the computer stone age.
.
To make this invocation form work, classical troff
macro packages used names that started with the letter \[oq]m\[cq],
which was omitted in the naming of the macro file.
.
.
.P
For example, the macro package for the man pages was called
.IR man ,
while its macro file
.IR tmac.an .
So it could be activated by the argument
.I an
to option
.BR \-m ,
or
.B \-man
for short.
.
.
.P
For similar reasons, macro packages that did not start with an
\[oq]m\[cq] had a leading \[oq]m\[cq] added in the documentation and
in speech; for example, the package corresponding to
.I tmac.doc
was called
.I mdoc
in the documentation, although a more suitable name would be
.IR doc .
For, when omitting the space between the option and its argument, the
command-line option for activating this package reads
.BR \-mdoc .
.
.
.P
To cope with all situations, actual versions of
.IR groff (@MAN1EXT@)
are smart about both naming schemes by providing two macro files
for the inflicted macro packages; one with a leading \[oq]m\[cq]
the other one without it.
.
So in
.IR groff ,
the
.I man
macro package may be specified as one of the following four methods:
.
.IP
.EX
\fIsh#\fP groff\ \-m\ man
\fIsh#\fP groff\ \-man
\fIsh#\fP groff\ \-mman
\fIsh#\fP groff\ \-m\ an
.EE
.
.
.P
Recent packages that do not start with \[oq]m\[cq] do not use an
additional \[oq]m\[cq] in the documentation.
.
For example, the
.I www
macro package may be specified only as one of the two methods:
.
.IP
.EX
\fIsh#\fP groff\ \-m\ www
\fIsh#\fP groff\ \-mwww
.EE
.
.
.P
Obviously, variants like
.I \-mmwww
would not make much sense.
.
.
.P
A second strange feature of classical troff was to name macro files
in the form
.IR tmac. name.
In modern operating systems, the type of a file is specified as a
postfix, the file name extension.
.
Again,
.I groff
copes with this situation by searching for both
.IB anything .tmac
and
.BI tmac. anything
if only
.I anything
is specified.
.
.
.P
The easiest way to find out which macro packages are available on a
system is to check the man\~page
.IR groff (@MAN1EXT@),
or the contents of the
.I tmac
directories.
.
.
.P
In
.IR groff ,
most macro packages are described in\~man pages called
.IR groff_ name(@MAN7EXT@),
with a leading \[oq]m\[cq] for the classical packages.
.
.
.\" ====================================================================
.SH Inclusion
.\" ====================================================================
.
There are several ways to use a macro package in a document.
.
The classical way is to specify the troff/groff option
.B \-m
.I name
at run time; this makes the contents of the macro package
.I name
available.
.
In groff, the file
.RI name .tmac
is searched within the tmac path; if not found,
.IR tmac. name
is searched for instead.
.
.
.P
Alternatively, it is also possible to include a macro file by adding
the request
.B .so
.I filename
to the document; the argument must be the full file name of an
existing file, possibly with the directory where it is kept.
.
In groff, this was improved by the similar request
.B .mso
.IR package ,
which added searching in the tmac path, just like option
.B \-m
does.
.
.
.P
In order to resolve the
.B .so
and
.B .mso
requests,
the roff preprocessor
.IR \%@g@soelim (@MAN1EXT@)
must be called if the files to be included need preprocessing.
.
This can be done either directly by a pipeline on the command line or
by using the troff/groff option
.BR \-s .
.
.I man
calls soelim automatically.
.
.
.P
For example, suppose a macro file is stored as
.
.IP
.I @MACRODIR@/macros.tmac
.
.P
and is used in some document called
.IR docu.roff .
.
.
.P
At run time, the formatter call for this is
.
.IP
.EX
\fIsh#\fP groff \-m macros docu.roff
.EE
.
.
.P
To include the macro file directly in the document, use either
.
.IP
.EX
\&.mso macros.tmac
.EE
.
.P
or
.
.IP
.EX
\&.so @MACRODIR@/macros.tmac
.EE
.
.
.P
In both cases, the formatter should be called with option
.B \-s
to invoke
.IR \%@g@soelim .
.IP
.EX
\fIsh#\fP groff \-s docu.roff
.EE
.
.
.ig
.\" ====================================================================
.SH Convention
.\" ====================================================================
.
.\" This section does not fit into the framework of this document.
.
There is a convention that is supported by many modern roff
typesetters and
.IR man (1)
programs, the
.I preprocessor word
described in the following.
.
.P
If the first line in a document is a comment, the first word (after the
comment characters and a blank) constitutes the
.B preprocessor
.BR word .
That means that the letters of this word are interpreted as
abbreviations for those preprocessor commands that should be run
when formatting the document.
.
Mostly, only the letters corresponding to the options for the
preprocessors are recognized,
\[oq]e\[cq]
(for
.IR eqn ),
.\" \[oq]G\[cq],
.\" \[oq]g\[cq],
\[oq]p\[cq]
(for
.IR pic ),
\[oq]R\[cq]
(for
.IR refer ),
\[oq]s\[cq]
(for
.IR soelim ),
and
\[oq]t\[cq]
(for
.IR tbl ).
(see
.IR roff (@MAN7EXT@)).
.
.
.P
Besides being a good reminder for the user, some formatters (like the
.IR man (1)
program) are even able to automatically start the preprocessors
specified in the preprocessor word, but do not bet on this.
.
.
.P
The
.I man
program handles some preprocessors automatically, such that in
man\~pages only the following characters should be used:
\[oq]e\[cq], \[oq]p\[cq], and \[oq]t\[cq].
.
.
..
.\" ====================================================================
.SH "Writing macros"
.\" ====================================================================
.
A
.IR roff (@MAN7EXT@)
document is a text file that is enriched by predefined formatting
constructs, such as requests, escape sequences, strings, numeric
registers, and macros from a macro package.
.
These elements are described in
.IR roff (@MAN7EXT@).
.
.
.P
To give a document a personal style, it is most useful to extend the
existing elements by defining some macros for repeating tasks; the best
place for this is near the beginning of the document or in a separate
file.
.
.
.P
Macros without arguments are just like strings.
.
But the full power of macros occurs when arguments are passed with a
macro call.
.
Within the macro definition, the arguments are available as the escape
sequences
.BR \[rs]$1 ,
\&.\|.\|.,
.BR \[rs]$9 ,
.BR \[rs]$[ .\|.\|. ] ,
.BR \[rs]$* ,
and
.BR \[rs]$@ ,
the name under which the macro was called is in
.BR \[rs]$0 ,
and the number of arguments is in register
.BR \[rs]n[.$] ;
see
.IR groff (@MAN7EXT@).
.
.
.\" ====================================================================
.SS "Draft mode"
.\" ====================================================================
.
Writing groff macros is easy when the escaping mechanism is temporarily
disabled.
.
In groff, this is done by enclosing the macro definition(s) within a
pair of
.B .eo
and
.B .ec
requests.
.
Then the body in the macro definition is just like a normal part of
the document \[em] text enhanced by calls of requests, macros,
strings, registers, etc.
.
For example, the code above can be written in a simpler way by
.
.
.IP
.ds @1 \[rs]f[I]\[rs]$0\[rs]f[]\"
.ds @2 arguments:\"
.EX
\&.eo
\&.ds midpart was called with the following
\&.de print_args
\&\*[@1]\ \[rs]*[midpart]\ \[rs]n[.$]\ \*[@2]
\&\[rs]$*
\&..
\&.ec
.EE
.rm @1
.rm @2
.
.
.P
Unfortunately, draft mode cannot be used universally.
.
Although it is good enough for defining normal macros, draft mode
fails with advanced applications, such as indirectly defined
strings, registers, etc.
.
An optimal way is to define and test all macros in draft mode and then
do the backslash doubling as a final step; do not forget to remove the
.I .eo
request.
.
.
.\" ====================================================================
.SS "Tips for macro definitions"
.\" ====================================================================
.
.IP \(bu
Start every line with a dot, for example, by using the groff request
.B .nop
for text lines, or write your own macro that handles also text lines
with a leading dot.
.
.RS
.IP
.EX
\&.de Text
\&.\ \ if (\[rs]\[rs]n[.$] == 0)\ \[rs]
\&.\ \ \ \ return
\&.\ \ nop\ \[rs])\[rs]\[rs]$*\[rs])
\&..
.EE
.RE
.
.IP \(bu
Write a comment macro that works both for copy and draft modes;
since the escape character is off in draft mode,
trouble might occur when comment escapes are used.
.
For example, the following macro just ignores its arguments, so it
acts like a comment line:
.
.RS
.IP
.EX
\&.de\ c
\&..
\&.c\ This\ is\ like\ a\ comment\ line.
.EE
.RE
.
.IP \(bu
In long macro definitions, make ample use of comment lines or
almost-empty lines (this is, lines which have a leading dot
and nothing else) for a better structuring.
.
.IP \(bu
To increase readability, use groff's indentation facility for
requests and macro calls (arbitrary whitespace after the leading dot).
.
.
.\" ====================================================================
.SS Diversions
.\" ====================================================================
.
Diversions can be used to implement quite advanced programming
constructs.
.
They are comparable to pointers to large data structures in the
C\~programming language, but their usage is quite different.
.
.
.P
In their simplest form, diversions are multi-line strings, but
diversions get their power when used dynamically within macros.
.
The (formatted) information stored in a diversion can be retrieved by
calling the diversion just like a macro.
.
.
.P
Most of the problems arising with diversions can be avoided if you
remember that diversions always store complete lines.
.
Using diversions when the line buffer has not been flushed produces
strange results; not knowing this, many people get desperate about
diversions.
.
To ensure that a diversion works, add line breaks at the right
places.
.
To be safe, enclose everything that has to do with diversions within
a pair of line breaks; for example, by explicitly using
.B .br
requests.
.
This rule should be applied to diversion definition, both inside and
outside, and to all calls of diversions.
.
This is a bit of overkill, but it works nicely.
.
.
.P
(If you really need diversions which should ignore the current partial
line, use environments to save the current partial line and/\:or use the
.B .box
request.)
.
.
.P
The most powerful feature using diversions is to start a diversion
within a macro definition and end it within another macro.
.
Then everything between each call of this macro pair is stored within
the diversion and can be manipulated from within the macros.
.
.
.\" ====================================================================
.SH Authors
.\" ====================================================================
.
This document was written by
.MT groff\-bernd\:.warken\-72@\:web\:.de
Bernd Warken
.ME
and
.MT wl@\:gnu\:.org
Werner Lemberg
.ME .
.
.
.\" ====================================================================
.SH "See also"
.\" ====================================================================
.
.IR "Groff: The GNU Implementation of troff" ,
by Trent A.\& Fisher and Werner Lemberg,
is the primary
.I groff
manual.
.
You can browse it interactively with \[lq]info groff\[rq].
.
.
.LP
The
.UR https://wiki.linuxfoundation.org/lsb/fhs
Filesystem Hierarchy Standard
.UE
is maintained by the Linux Foundation.
.
.
.TP
.IR groff (@MAN1EXT@)
is an overview of the
.I groff
system.
.
.
.TP
.IR groff_man (@MAN7EXT@),
.TQ
.IR groff_mdoc (@MAN7EXT@),
.TQ
.IR groff_me (@MAN7EXT@),
.TQ
.IR groff_mm (@MAN7EXT@),
.TQ
.IR groff_mom (@MAN7EXT@),
.TQ
.IR groff_ms (@MAN7EXT@),
.TQ
.IR groff_rfc1345 (@MAN7EXT@),
.TQ
.IR groff_trace (@MAN7EXT@),
\~and
.TQ
.IR groff_www (@MAN7EXT@)
are
.I groff
macro packages.
.
.
.TP
.IR groff (@MAN7EXT@)
summarizes the language recognized by GNU
.IR troff . \" GNU
.
.
.\" Restore compatibility mode (for, e.g., Solaris 10/11).
.cp \n[*groff_groff_tmac_5_man_C]
.do rr *groff_groff_tmac_5_man_C
.
.
.\" Local Variables:
.\" fill-column: 72
.\" mode: nroff
.\" End:
.\" vim: set filetype=groff textwidth=72:
