export
GROFF_BIN_PATH := ..
GROFF_FONT_PATH := ../font
GROFF_TMAC_PATH := ../tmac

dankeCJK.ps: dankeCJK.1
	groff -K utf8 -T ps ./dankeCJK.1 > ./dankeCJK.ps

dankeJK0.ps: dankeJK0.1
	groff -K utf8 -T ps ./dankeJK0.1 > ./dankeJK0.ps

dankeJK1.ps: dankeJK1.1
	groff -K utf8 -T ps ./dankeJK1.1 > ./dankeJK1.ps

ningen0.ps: ningen0.1
	groff -K utf8 -T ps -m ja ./ningen0.1 > ./ningen0.ps

ningen1.ps: ningen1.1
	groff -K utf8 -T ps -m ja ./ningen1.1 > ./ningen1.ps

ningen2.ps: ningen2.1
	groff -K utf8 -T ps -m ja ./ningen2.1 > ./ningen2.ps

ningen3.ps: ningen3.1
	groff -K utf8 -T ps -m ja ./ningen3.1 > ./ningen3.ps

