.TH grog @MAN1EXT@ "@MDATE@" "groff @VERSION@"
.SH Name
grog \- \(lqgroff guess\(rq\(eminfer a document's groff command
.
.
.\" ====================================================================
.\" Legal Terms
.\" ====================================================================
.\"
.\" Copyright (C) 1989-2021 Free Software Foundation, Inc.
.\"
.\" This file is part of grog, which is part of groff, a free software
.\" project.  You can redistribute it and/or modify it under the terms
.\" of the GNU General Public License version 2 (GPL2) as published by
.\" the Free Software Foundation.
.\"
.\" groff is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\" The text for GPL2 is available in the internet at
.\" <http://www.gnu.org/licenses/gpl2.0.txt>.
.
.
.\" Save and disable compatibility mode (for, e.g., Solaris 10/11).
.do nr *groff_grog_1_man_C \n[.cp]
.cp 0
.
.
.\" ====================================================================
.SH Synopsis
.\" ====================================================================
.
.SY grog
.OP \-\-run
.OP \-\-warnings
.OP \-\-ligatures
.RI [ groff-option
\&.\|.\|.\&]
.OP \-\-
.RI [ file
\&.\|.\|.]
.YS
.
.
.SY grog
.B \-h
.
.SY grog
.B \-\-help
.YS
.
.
.SY grog
.B \-v
.
.SY grog
.B \-\-version
.YS
.
.
.\" ====================================================================
.SH Description
.\" ====================================================================
.
.I grog
reads the input
(file names or standard input)
and guesses which
.IR groff (@MAN1EXT@)
options are needed to render the input with the
.I groff
program.
.
If no operands are given,
or if
.I file
is
.RB \[lq] \- \[rq],
.I grog
reads the standard input stream.
.
The corresponding
.I groff
command is normally written to the standard output stream.
.
With the option
.BR \-\-run ,
the generated command is written to the standard error stream and then
executed.
.
.
.\" ====================================================================
.SH Options
.\" ====================================================================
.
.B \-h
and
.B \-\-help
display a usage message,
whereas
.B \-v
and
.B \-\-version
display version information;
all exit afterward.
.
.
.TP
.B \-\-ligatures
forces inclusion of the arguments
.B \-P\-y \-PU
in the generated
.I groff
command.
.
.
.TP
.B \-\-run
writes the inferred command to the standard error stream and then
executes it.
.
.
.TP
.B \-\-warnings
issues more warnings to the standard error stream.
.
.
.P
All other specified short options
(words starting with one minus character
.RB \[lq] \- \[rq])
are interpreted as
.I groff
options or option clusters with or without argument.
.
No space is allowed between such an option and its argument when it is
specified to
.IR grog ;
this is not the case for
.I groff
itself.
.
Except for
.BR \-m ,
these options are passed through;
that is,
they are included unchanged in the output command without affecting the
work of
.IR grog .
.
.
.\" ====================================================================
.SH Details
.\" ====================================================================
.
.I grog
reads all
.I file
operands in their entirety,
pattern-matching strings that are statistically likely to be
characteristic of
.IR roff (@MAN7EXT@)
documents.
.
It tries to guess which of the following
.I groff
options are required to correctly render the input:
.BR \-e ,
.BR \-g ,
.BR \-G ,
.BR \-j ,
.\" gideal is not implemented yet.
.\" .BR \-J ,
.BR \-p ,
.BR \-R ,
.BR \-s ,
.B \-t
(preprocessors);
and
.BR \-man ,
.BR \-mdoc ,
.BR \-mdoc\-old ,
.BR \-me ,
.BR \-mm ,
.BR \-mom ,
and
.B \-ms
(macro packages).
.
The inferred
.I groff
command including those options and any
.I file
parameters is written to the standard output stream.
.
.
.P
It is possible to specify arbitrary
.I groff
options on the command line.
.
These are included in the inferred command without change,
except for the
.B \-m
options.
.
Choices of
.I groff
options include
.B \-C
to enable compatibility mode and
.B \-T
to specify an output device other than the default.
.
.
.P
.I groff
may issue diagnostic messages when an inappropriate
.B \-m
option,
or multiple conflicting ones,
are specified.
.
Consequently,
it is best to specify no
.B \-m
options to
.I grog
unless it cannot correctly infer any
.B \-m
arguments at all.
.
.I grog
will only accept
.B \-m
arguments and exit successfully if it can infer no
.I groff
.B \-m
argument from the input or if the inferred and specified
.B \-m
arguments agree.
.
.
.P
If multiple
.B \-m
options are inferred by
.IR grog ,
it emits a diagnostic and terminates with an error exit status.
.
The inferred command is written with the wrong options nevertheless.
.
.
.P
A
.I roff
document can also be written without recourse to any macro package.
.
In such cases,
.I grog
will infer a
.I groff
command without an
.B \-m
option.
.
.
.\" ====================================================================
.SH Examples
.\" ====================================================================
.
Running
.
.RS
.EX
.B grog meintro.me
.EE
.RE
at the command line results in
.RS
.EX
groff \-T ps \-me meintro.me
.EE
.RE
.
because
.I grog
recognizes that the file
.B meintro.me
is written using macros from the
.I me
package.
.
The command
.
.RS
.EX
.B grog pic.ms
.EE
.RE
.
outputs
.
.RS
.EX
groff \-T ps \-t \-e \-p \-ms pic.ms
.EE
.RE
.
on the other hand.
.
Besides discerning the
.I ms
macro package,
.I grog
recognizes that the file
.B pic.ms
additionally needs
.BR \-pte ,
the combination of
.B \-p
for
.IR pic ,
.B \-t
for
.IR tbl ,
and
.B \-e
for
.IR eqn .
.
.
.P
If both of the former example files are combined in the command
.
.RS
.EX
.B grog meintro.me pic.ms
.EE
.RE
.
a diagnostic message is sent to the standard error stream because some
macro packages cannot be combined.
.
Nevertheless the corresponding output with the wrong options is written
to standard output:
.
.RS
.EX
groff \-T ps \-t \-e \-p \-ms meintro.me pic.ms
.EE
.RE
.
and
.I grog
terminates with an error exit status.
.
.
.P
The command
.
.RS
.EX
.B grog \-ksS \-Tdvi grnexmpl.g
.EE
.RE
.
contains several
.I groff
options that are passed through without interference from
.IR grog .
.
These are the option cluster
.B \-ksS
and the typesetter option
.B \-T
with argument
.BR dvi .
.
The output is
.
.RS
.EX
groff \-k \-s \-S \-T dvi grnexmpl.g
.EE
.RE
.
so no additional option was added by
.IR grog .
.
As no
.B \-m
option was inferred by
.IR grog ,
this file does not use a macro package.
.
.
.\" ====================================================================
.SH Authors
.\" ====================================================================
.
.I grog
was originally written by James Clark.
.
The current Perl implementation was written by
.MT groff\-bernd\:.warken\-72@\:web\:.de
Bernd Warken
.ME
with contributions from Ralph Corderoy.
.
.
.\" ====================================================================
.SH "See also"
.\" ====================================================================
.
.IR groff (@MAN1EXT@)
.
.
.\" Restore compatibility mode (for, e.g., Solaris 10/11).
.cp \n[*groff_grog_1_man_C]
.
.
.\" Local Variables:
.\" fill-column: 72
.\" mode: nroff
.\" End:
.\" vim: set filetype=groff textwidth=72:
