.TH mmroff @MAN1EXT@ "@MDATE@" "groff @VERSION@"
.SH Name
mmroff \- cross-referencing front end for GNU roff mm macro package
.
.
.\" ====================================================================
.\" Legal Terms
.\" ====================================================================
.\"
.\" Copyright (C) 1989-2020 Free Software Foundation, Inc.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided that
.\" the entire resulting derived work is distributed under the terms of
.\" a permission notice identical to this one.
.\"
.\" Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for
.\" modified versions, except that this permission notice may be
.\" included in translations approved by the Free Software Foundation
.\" instead of in the original English.
.
.
.\" Save and disable compatibility mode (for, e.g., Solaris 10/11).
.do nr *groff_mmroff_1_man_C \n[.cp]
.cp 0
.
.
.\" ====================================================================
.SH Synopsis
.\" ====================================================================
.
.SY mmroff
.OP \-x
.I groff-arguments
.YS
.
.
.\" ====================================================================
.SH Description
.\" ====================================================================
.
.I mmroff
is a simple preprocessor for
.IR groff ,
used for expanding cross references in
.IR m@TMAC_M_PREFIX@m ;
see
.IR groff_mm (@MAN7EXT@).
.
.I groff
is executed twice,
first with
.B \-z
and
.B \-rRef=1
to collect all cross references and then to do the real processing
when the cross-reference file is up to date.
.
.
.\" ====================================================================
.SH Options
.\" ====================================================================
.
.TP
.B \-x
Just create the cross-reference file.
.
This can be used to refresh the cross-reference file;
it isn't always needed to have accurate cross references and by using
this option
.I groff
will only be run once.
.
.
.\" ====================================================================
.SH Authors
.\" ====================================================================
.
.I mmroff
was written by
.MT jh@\:axis\:.se
J\[o ad]rgen H\[a ad]gg
.ME
of Lund,
Sweden.
.
.
.\" ====================================================================
.SH "See also"
.\" ====================================================================
.
.IR groff_mm (@MAN7EXT@),
.IR groff_mmse (@MAN7EXT@),
.IR groff (@MAN1EXT@),
.IR \%@g@troff (@MAN1EXT@),
.IR \%@g@tbl (@MAN1EXT@),
.IR \%@g@pic (@MAN1EXT@),
.IR \%@g@eqn (@MAN1EXT@)
.
.
.\" Restore compatibility mode (for, e.g., Solaris 10/11).
.cp \n[*groff_mmroff_1_man_C]
.
.
.\" Local Variables:
.\" fill-column: 72
.\" mode: nroff
.\" End:
.\" vim: set filetype=groff textwidth=72:
